ru:
  devvault:
      vk.poster:
          userId: 243463  # ИД пользователя из запроса
          accessToken: "d010d0048d5900000b50330d0d0e00000ea67e9fc9d0000001e1a1155f1958f6f6a0e1247641da8610000"  # Токен доступа
          tags:  # Перечисление тэгов с группами
            - "Группы по продаже"  # Тег 1
            - "Группы объявлений"  # Тег 2
          postMessage: "Продам гараж, срочно, мой телефон +7 (999) 399 29 29"  # Сообщение, которое нужно распространить
          postMessageQuery: "Продам гараж"  # Строка, по которой необходимо искать предыдущие сообщения (если есть то сообщение создаваться не будет)
          postToGroups: true  # Выкладывать ли сообщения в группы
          postToGroupsTopics: true  # Выкладывать ли сообщения в обсуждения
          tagPagesQuerySize: 50  # Размер страницы запроса грууп в тегах
          groupPostQuerySize: 15  # Размер страницы запроса сообщений из групп по которым производить поиск
          groupTopicQuerySize: 10  # Размер страницы запроса сообщений из обсуждений групп по которым производить поиск